[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    regression: Маркировка для регресса
    courses:  Маркировки тестов страницы курса
    registration: Маркировка для формы регистрации
    dashboard: Маркировка для тестов, связанных с рабочей панелью
    authorization: Маркировка  формы авторизации

